import { callPlanner, callCoder, callReviewer } from "./llm";
import { applyUnifiedDiff, commitAll, createBranch, currentDiff, ensureCleanGit, ghCreatePr, pushBranch } from "./git";
import { runQa } from "./tools";

function readGoalFromArgsOrEnv() {
  const goalFromEnv = process.env.AGENT_GOAL;
  const goalFromArgs = process.argv.slice(2).join(" ").trim();
  const goal = (goalFromEnv ?? goalFromArgs).trim();
  if (!goal) throw new Error('Missing goal. Usage: bun run agent -- "your goal" or set AGENT_GOAL.');
  return goal;
}

async function main() {
  const goal = readGoalFromArgsOrEnv();

  const baseBranch = process.env.AGENT_BASE_BRANCH ?? "main";
  const maxIters = Number(process.env.AGENT_MAX_ITERS ?? "4");
  const createPr = (process.env.AGENT_CREATE_PR ?? "false").toLowerCase() === "true";

  await ensureCleanGit();

  const branch = await createBranch(baseBranch);
  console.log(`[agent] branch=${branch} base=${baseBranch}`);

  const plan = await callPlanner({ goal, context: {} });
  console.log(`[agent] planned tasks: ${plan.tasks.map((t) => t.id).join(", ")}`);

  for (const task of plan.tasks) {
    console.log(`\n[agent] Task ${task.id}: ${task.title}`);

    let reviewerFeedback = "";
    for (let i = 1; i <= maxIters; i++) {
      console.log(`[agent] iteration ${i}/${maxIters}`);

      const diffBefore = await currentDiff();

      const coderOut = await callCoder({
        goal,
        task,
        context: {},
        reviewerFeedback,
      });

      await applyUnifiedDiff(coderOut.diff);

      const committed = await commitAll(`agent: ${task.id} ${coderOut.summary}`);
      if (!committed) console.log("[agent] nothing to commit after patch");

      const qa = await runQa();
      console.log(`[agent] QA ok=${qa.ok}`);
      const qaSummary = qa.summary;

      const diffAfter = await currentDiff();
      const reviewer = await callReviewer({
        goal,
        task,
        diff: diffAfter || diffBefore,
        qaSummary,
      });

      if (qa.ok && reviewer.approved) {
        console.log(`[agent] reviewer approved task ${task.id}`);
        break;
      }

      reviewerFeedback = [
        `QA ok=${qa.ok}`,
        `QA logs:\n${qaSummary}`,
        `Reviewer comments:\n${reviewer.comments.join("\n")}`,
        `Required changes:\n${reviewer.required_changes.join("\n")}`,
      ].join("\n");

      if (i === maxIters) throw new Error(`Task ${task.id} failed after ${maxIters} iterations`);
    }
  }

  await pushBranch(branch);
  console.log(`[agent] pushed ${branch}`);

  if (createPr) {
    const title = `Agent: ${goal}`;
    const body = [`Auto-generated by agent-runner.`, ``, `Mode: ${process.env.AGENT_MODE ?? "mock"}`, `Goal: ${goal}`].join("\n");
    await ghCreatePr(title, body, baseBranch, branch);
    console.log("[agent] PR created");
  } else {
    console.log("[agent] AGENT_CREATE_PR=false, skipping PR creation");
  }
}

main().catch((e) => {
  console.error("[agent] ERROR:", e?.stack || e);
  process.exit(1);
});
